---@class Palette
---@field bg string
---@field fg string
---@field selection string
---@field comment string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field purple string
---@field cyan string
---@field pink string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_magenta string
---@field bright_cyan string
---@field bright_white string
---@field menu string
---@field visual string
---@field gutter_fg string
---@field nontext string
---@field white string
---@field black string
return {
   bg = "#141423",
   fg = "#F8F8F2",
   selection = "#2D2D4E",
   comment = "#6272A4",
   red = "#FF5555",
   orange = "#FFB86C",
   yellow = "#F1FA8C",
   green = "#50fa7b",
   purple = "#BD93F9",
   cyan = "#2CCCFF",
   pink = "#FF79C6",
   bright_red = "#FF6E6E",
   bright_green = "#20E3B2",
   bright_yellow = "#FFFFA5",
   bright_blue = "#D6ACFF",
   bright_magenta = "#FF92DF",
   bright_cyan = "#2CCCFF",
   bright_white = "#FFFFFF",
   menu = "#21222C",
   visual = "#555594",
   gutter_fg = "#4B5263",
   nontext = "#3B4048",
   white = "#F8F8F2",
   black = "#191A21",
}
